In [1]:
import pandas as pd
import numpy as np

In [31]:
data = np.random.randint(0,100,[10,5])
df = pd.DataFrame(data,
                  index=['A','B','C','D','E','F','G','H','I','J'],
                  columns=['a','b','c','d','e'])
print('df')
df

df


a   b   c   d   e
A  26  23  52  88  25
B   0  53  64  92  37
C  44  74  92  74  70
D  53  59  80  19  23
E  57  68  76  25  99
F  49  65  24  35  12
G  72   4  14   7  47
H   0  34  38  45  66
I  86  36  54  79  40
J  51   8   7  47  67

In [24]:
print('max()')
df.max()

max()


a    85
b    77
c    83
d    84
e    92
dtype: int64

#idxmax
df.idxmax()

In [25]:
print('idxmax()')
df.idxmax()

idxmax()


a    C
b    B
c    F
d    B
e    G
dtype: object

In [59]:
import time
arr = np.random.randint(0,100,[10**5,10**4],dtype='int8')
arr

array([[79, 97, 10, ..., 79, 84, 64],
       [90, 64, 18, ..., 68, 11, 94],
       [54, 54, 45, ..., 78, 36, 66],
       ...,
       [ 0, 12, 94, ..., 34,  2, 24],
       [ 7, 95, 80, ..., 45, 66, 52],
       [ 7, 74, 35, ..., 51, 87,  8]], dtype=int8)

In [60]:
df = pd.DataFrame(arr, dtype='int8')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 10000 entries, 0 to 9999
dtypes: int8(10000)
memory usage: 953.7 MB


In [61]:
ts = time.time()
df.max()
te =time.time()
print('max()_time:',te-ts)
ts = time.time()
df.idxmax()
te =time.time()
print('idxmax()_time:',te-ts)

max()_time: 10.667221784591675
idxmax()_time: 19.077805042266846


In [14]:
import inspect
print(inspect.getsource(pd.DataFrame.idxmax))

    def idxmax(self, axis=0, skipna=True):
        """
        Return index of first occurrence of maximum over requested axis.
        NA/null values are excluded.

        Parameters
        ----------
        axis : {0 or 'index', 1 or 'columns'}, default 0
            0 or 'index' for row-wise, 1 or 'columns' for column-wise
        skipna : boolean, default True
            Exclude NA/null values. If an entire row/column is NA, the result
            will be NA.

        Returns
        -------
        idxmax : Series

        Raises
        ------
        ValueError
            * If the row/column is empty

        See Also
        --------
        Series.idxmax

        Notes
        -----
        This method is the DataFrame version of ``ndarray.argmax``.
        """
        axis = self._get_axis_number(axis)
        indices = nanops.nanargmax(self.values, axis=axis, skipna=skipna)
        index = self._get_axis(axis)
        result = [index[i] if i >= 0 else np.nan for i in in

In [55]:
arr.shape

(100000, 10000)

In [62]:
ts = time.time()
_max = np.max(arr,axis=0)
te =time.time()
print('max()_time:',te-ts)

ts = time.time()
_argmax = np.argmax(arr,axis=0)
te =time.time()
print('argmax()_time:',te-ts)

max()_time: 0.8477091789245605
argmax()_time: 13.701550960540771


In [63]:
print(_max)

[99 99 99 ... 99 99 99]


In [65]:
print(_argmax)

[56 78  3 ... 30  7 21]
